services:
  bulk-ingest:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRACTUSMIND_REF: fc53778908d6e8bb7d30059f719a67e61b5450f0
    env_file:
      - .env
    gpus: all
    shm_size: "8gb"
    volumes:
      - ./.model-cache:/models
      - ./state:/state
    restart: "no"
